package main

import (
	"fmt"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func renderCIndex(findingsPath string, findings []finding, cSymbols []cSymbol, resolvedCRT []cSymbol) []byte {
	var b strings.Builder
	sort.SliceStable(findings, func(i, j int) bool {
		if findings[i].SourceFile == findings[j].SourceFile {
			return findings[i].Address < findings[j].Address
		}
		return findings[i].SourceFile < findings[j].SourceFile
	})

	b.WriteString("/*\n")
	b.WriteString(" * Generated by tools/lt2findings from ")
	b.WriteString(findingsPath)
	b.WriteString(".\n")
	b.WriteString(" * Do not edit by hand; edit the findings file and run:\n")
	b.WriteString(" *   go run ./tools/lt2findings -write\n")
	b.WriteString(" *\n")
	b.WriteString(" * Every address below is scoped to the individual source_file named by\n")
	b.WriteString(" * decompiled/findings/findings.ini.\n")
	b.WriteString(" *\n")
	b.WriteString(" * Define LT2_FINDING before including this file to consume address-backed\n")
	b.WriteString(" * records. Define LT2_C_SYMBOL to consume every recovered C symbol,\n")
	b.WriteString(" * including source-only helpers that do not yet have a trustworthy\n")
	b.WriteString(" * program address. Define LT2_FINDING_TAG and LT2_C_SYMBOL_TAG to\n")
	b.WriteString(" * consume normalized tags without parsing comments or ids. Resolved CRT\n")
	b.WriteString(" * wrappers are generated from Ghidra JSONL analysis events when present.\n")
	b.WriteString(" */\n")
	b.WriteString("#ifndef LT2_FINDINGS_INDEX_H\n")
	b.WriteString("#define LT2_FINDINGS_INDEX_H\n\n")
	b.WriteString("#ifndef LT2_FINDING\n")
	b.WriteString("#define LT2_FINDING(id, source_file, program, address, kind, label, c_symbol, title, comment)\n")
	b.WriteString("#define LT2_FINDING_WAS_UNDEFINED 1\n")
	b.WriteString("#endif\n\n")
	b.WriteString("#ifndef LT2_C_SYMBOL\n")
	b.WriteString("#define LT2_C_SYMBOL(kind, name, source_path, line, linked_finding_id)\n")
	b.WriteString("#define LT2_C_SYMBOL_WAS_UNDEFINED 1\n")
	b.WriteString("#endif\n\n")
	b.WriteString("#ifndef LT2_FINDING_TAG\n")
	b.WriteString("#define LT2_FINDING_TAG(finding_id, tag)\n")
	b.WriteString("#define LT2_FINDING_TAG_WAS_UNDEFINED 1\n")
	b.WriteString("#endif\n\n")
	b.WriteString("#ifndef LT2_C_SYMBOL_TAG\n")
	b.WriteString("#define LT2_C_SYMBOL_TAG(kind, name, source_path, line, tag)\n")
	b.WriteString("#define LT2_C_SYMBOL_TAG_WAS_UNDEFINED 1\n")
	b.WriteString("#endif\n\n")

	b.WriteString("/* Address-backed findings. */\n")
	for _, f := range findings {
		fmt.Fprintf(&b, "LT2_FINDING(%s, %s, %s, 0x%sU, %s, %s, %s, %s, %s)\n",
			cString(f.ID),
			cString(f.SourceFile),
			cString(f.Program),
			f.Address,
			cString(f.Kind),
			cString(f.Label),
			cString(f.CSymbol),
			cString(f.Title),
			cString(f.Comment),
		)
	}

	b.WriteString("\n/* Tags for address-backed findings. */\n")
	for _, f := range findings {
		for _, tag := range findingTags(f) {
			fmt.Fprintf(&b, "LT2_FINDING_TAG(%s, %s)\n",
				cString(f.ID),
				cString(tag),
			)
		}
	}

	b.WriteString("\n/* Recovered C/source symbols. */\n")
	for _, s := range cSymbols {
		fmt.Fprintf(&b, "LT2_C_SYMBOL(%s, %s, %s, %d, %s)\n",
			cString(s.Kind),
			cString(s.Name),
			cString(s.Source),
			s.Line,
			cString(s.FindingID),
		)
	}

	b.WriteString("\n/* Resolved CRT Wrappers. */\n")
	for _, s := range resolvedCRT {
		fmt.Fprintf(&b, "LT2_C_SYMBOL(%s, %s, %s, %d, %s)\n",
			cString(s.Kind),
			cString(s.Name),
			cString(s.Source),
			s.Line,
			cString(s.FindingID),
		)
	}

	b.WriteString("\n/* Tags for recovered functions and resolved wrappers. */\n")
	for _, s := range append(append([]cSymbol{}, cSymbols...), resolvedCRT...) {
		for _, tag := range cSymbolTags(s) {
			fmt.Fprintf(&b, "LT2_C_SYMBOL_TAG(%s, %s, %s, %d, %s)\n",
				cString(s.Kind),
				cString(s.Name),
				cString(s.Source),
				s.Line,
				cString(tag),
			)
		}
	}

	b.WriteString("\n#ifdef LT2_FINDING_WAS_UNDEFINED\n")
	b.WriteString("#undef LT2_FINDING\n")
	b.WriteString("#undef LT2_FINDING_WAS_UNDEFINED\n")
	b.WriteString("#endif\n")
	b.WriteString("#ifdef LT2_C_SYMBOL_WAS_UNDEFINED\n")
	b.WriteString("#undef LT2_C_SYMBOL\n")
	b.WriteString("#undef LT2_C_SYMBOL_WAS_UNDEFINED\n")
	b.WriteString("#endif\n")
	b.WriteString("#ifdef LT2_FINDING_TAG_WAS_UNDEFINED\n")
	b.WriteString("#undef LT2_FINDING_TAG\n")
	b.WriteString("#undef LT2_FINDING_TAG_WAS_UNDEFINED\n")
	b.WriteString("#endif\n")
	b.WriteString("#ifdef LT2_C_SYMBOL_TAG_WAS_UNDEFINED\n")
	b.WriteString("#undef LT2_C_SYMBOL_TAG\n")
	b.WriteString("#undef LT2_C_SYMBOL_TAG_WAS_UNDEFINED\n")
	b.WriteString("#endif\n")
	b.WriteString("\n#endif\n")
	return []byte(b.String())
}

func cString(s string) string {
	return strconv.Quote(s)
}

func findingTags(f finding) []string {
	domain := f.ID
	if i := strings.IndexByte(domain, '.'); i >= 0 {
		domain = domain[:i]
	}
	return compactTags([]string{
		"LT2",
		"LT2_KIND_" + safeTagPart(f.Kind),
		"LT2_PROGRAM_" + safeTagPart(f.Program),
		"LT2_DOMAIN_" + safeTagPart(domain),
		"LT2_FINDING_" + safeTagPart(f.ID),
	})
}

func cSymbolTags(s cSymbol) []string {
	switch s.Kind {
	case "function":
		tags := []string{
			"LT2",
			"LT2_C_FUNCTION",
			"LT2_SOURCE_" + safeTagPart(strings.TrimSuffix(filepath.Base(s.Source), filepath.Ext(s.Source))),
		}
		if s.FindingID != "" {
			tags = append(tags, "LT2_LINKED_FINDING_"+safeTagPart(s.FindingID))
		}
		return compactTags(tags)
	case "resolved_crt_wrapper":
		return compactTags([]string{
			"LT2",
			"LT2_RESOLVED_CRT_WRAPPER",
			"LT2_SOURCE_" + safeTagPart(strings.TrimSuffix(filepath.Base(s.Source), filepath.Ext(s.Source))),
		})
	default:
		return nil
	}
}

func compactTags(tags []string) []string {
	out := make([]string, 0, len(tags))
	seen := map[string]bool{}
	for _, tag := range tags {
		if tag == "" || seen[tag] {
			continue
		}
		seen[tag] = true
		out = append(out, tag)
	}
	return out
}

func safeTagPart(value string) string {
	if value == "" {
		return "unknown"
	}
	var b strings.Builder
	lastUnderscore := false
	for _, ch := range value {
		ok := (ch >= 'A' && ch <= 'Z') || (ch >= 'a' && ch <= 'z') ||
			(ch >= '0' && ch <= '9')
		if ok {
			b.WriteRune(ch)
			lastUnderscore = false
			continue
		}
		if b.Len() > 0 && !lastUnderscore {
			b.WriteByte('_')
			lastUnderscore = true
		}
	}
	return strings.TrimSuffix(b.String(), "_")
}
