package normalizer

var cleanImportManifest = []cleanImportDLL{
	{
		Name:          "GDI32.dll",
		FirstThunkRVA: 0x92000,
		Entries: namedImports(
			"GetObjectA",
			"CreateCompatibleDC",
			"BitBlt",
			"DeleteDC",
			"DeleteObject",
			"StretchBlt",
			"CreateDIBSection",
			"SelectObject",
			"GetDeviceCaps",
		),
	},
	{
		Name:          "KERNEL32.dll",
		FirstThunkRVA: 0x92028,
		Entries: namedImports(
			"CreateFileA",
			"LoadLibraryA",
			"GetOEMCP",
			"GetACP",
			"GetCPInfo",
			"InterlockedIncrement",
			"InterlockedDecrement",
			"IsBadCodePtr",
			"IsBadReadPtr",
			"GetStringTypeW",
			"GetStringTypeA",
			"MultiByteToWideChar",
			"SetUnhandledExceptionFilter",
			"FindClose",
			"FindNextFileA",
			"FindFirstFileA",
		),
	},
	{
		Name:          "ntdll.dll",
		FirstThunkRVA: 0x92068,
		Entries: namedImports(
			"RtlDeleteCriticalSection",
			"RtlInitializeCriticalSection",
			"RtlLeaveCriticalSection",
		),
	},
	{
		Name:          "KERNEL32.dll",
		FirstThunkRVA: 0x92074,
		Entries: namedImports(
			"GetModuleHandleA",
		),
	},
	{
		Name:          "ntdll.dll",
		FirstThunkRVA: 0x92078,
		Entries: namedImports(
			"RtlEnterCriticalSection",
		),
	},
	{
		Name:          "KERNEL32.dll",
		FirstThunkRVA: 0x9207C,
		Entries: namedImports(
			"GetSystemTime",
			"GetLocalTime",
			"GetVersionExA",
			"Sleep",
			"DeleteFileA",
			"GetTickCount",
			"GetModuleFileNameA",
			"OutputDebugStringA",
			"GetLastError",
			"CreateMutexA",
			"CloseHandle",
			"WaitForSingleObject",
			"SetEvent",
			"SetThreadPriority",
			"CreateThread",
			"CreateEventA",
			"GetCurrentThreadId",
			"SetStdHandle",
			"IsBadWritePtr",
			"VirtualAlloc",
			"SetFilePointer",
			"ReadFile",
			"WriteFile",
			"VirtualFree",
			"HeapCreate",
			"HeapDestroy",
			"GetEnvironmentVariableA",
			"GetFileType",
			"GetStdHandle",
			"SetHandleCount",
			"GetEnvironmentStringsW",
			"GetEnvironmentStrings",
			"WideCharToMultiByte",
			"FreeEnvironmentStringsW",
			"FreeEnvironmentStringsA",
			"UnhandledExceptionFilter",
			"GetProcAddress",
		),
	},
	{
		Name:          "ntdll.dll",
		FirstThunkRVA: 0x92110,
		Entries: namedImports(
			"RtlSizeHeap",
			"RtlReAllocateHeap",
		),
	},
	{
		Name:          "KERNEL32.dll",
		FirstThunkRVA: 0x92118,
		Entries: namedImports(
			"GetCurrentProcess",
			"TerminateProcess",
			"TlsGetValue",
			"SetLastError",
			"TlsAlloc",
			"TlsSetValue",
		),
	},
	{
		Name:          "ntdll.dll",
		FirstThunkRVA: 0x92130,
		Entries: namedImports(
			"RtlAllocateHeap",
		),
	},
	{
		Name:          "KERNEL32.dll",
		FirstThunkRVA: 0x92134,
		Entries: namedImports(
			"RaiseException",
			"HeapFree",
			"ExitProcess",
			"GetVersion",
			"GetCommandLineA",
			"GetStartupInfoA",
			"RtlUnwind",
			"InterlockedExchange",
			"FlushFileBuffers",
			"LCMapStringA",
			"LCMapStringW",
			"SetEndOfFile",
		),
	},
	{
		Name:          "TeneonIERelease.dll",
		FirstThunkRVA: 0x92168,
		Entries: namedImports(
			"??0IEBrowserContainer@@QAE@PAUHWND__@@@Z",
			"??1IEBrowserContainer@@QAE@XZ",
		),
	},
	{
		Name:          "USER32.dll",
		FirstThunkRVA: 0x92174,
		Entries: namedImports(
			"SetWindowLongA",
			"GetWindowPlacement",
			"GetWindowLongA",
		),
	},
	{
		Name:          "ntdll.dll",
		FirstThunkRVA: 0x92180,
		Entries: namedImports(
			"NtdllDefWindowProc_A",
		),
	},
	{
		Name:          "USER32.dll",
		FirstThunkRVA: 0x92184,
		Entries: namedImports(
			"SetFocus",
			"EnableWindow",
			"SetActiveWindow",
			"DestroyWindow",
			"CreateWindowExA",
			"RegisterClassA",
			"LoadCursorA",
			"ShowWindow",
			"MoveWindow",
			"MessageBoxA",
			"SetCapture",
			"SetWindowPlacement",
			"RegisterWindowMessageA",
			"LoadIconA",
			"PostMessageA",
			"DispatchMessageA",
			"PeekMessageA",
			"TranslateMessage",
			"PostQuitMessage",
			"PostThreadMessageA",
			"UpdateWindow",
			"SetForegroundWindow",
			"LoadBitmapA",
			"ReleaseDC",
			"GetDesktopWindow",
			"GetWindowRect",
			"GetDC",
			"ChangeDisplaySettingsA",
			"EnumDisplaySettingsA",
			"AdjustWindowRectEx",
			"SetWindowPos",
			"ClientToScreen",
			"GetClientRect",
			"OffsetRect",
			"ClipCursor",
			"GetKeyboardState",
			"GetKeyState",
			"GetAsyncKeyState",
			"ReleaseCapture",
		),
	},
	{
		Name:          "WS2_32.dll",
		FirstThunkRVA: 0x92224,
		Entries:       ordinalImports(115, 23, 8, 9, 52, 3, 4, 22, 19, 16, 116, 18),
	},
	{
		Name:          "fmod.dll",
		FirstThunkRVA: 0x92258,
		Entries: namedImports(
			"_FSOUND_Sample_Load@16",
			"_FSOUND_GetError@0",
			"_FSOUND_SetPaused@8",
			"_FSOUND_StopSound@4",
			"_FSOUND_Sample_Free@4",
			"_FSOUND_SetLoopMode@8",
			"_FSOUND_SetPriority@8",
			"_FSOUND_SetVolume@8",
			"_FSOUND_SetFrequency@8",
			"_FSOUND_SetMute@8",
			"_FMUSIC_PlaySong@4",
			"_FMUSIC_StopSong@4",
			"_FMUSIC_SetMasterVolume@8",
			"_FMUSIC_SetPanSeperation@8",
			"_FMUSIC_SetOrder@8",
			"_FMUSIC_SetLooping@8",
			"_FMUSIC_GetPaused@4",
			"_FMUSIC_SetPaused@8",
			"_FMUSIC_IsFinished@4",
			"_FMUSIC_IsPlaying@4",
			"_FMUSIC_LoadSongMemory@8",
			"_FSOUND_Init@12",
			"_FSOUND_Close@0",
			"_FSOUND_PlaySound@8",
		),
	},
}

func namedImports(names ...string) []cleanImportEntry {
	entries := make([]cleanImportEntry, len(names))
	for index, name := range names {
		entries[index] = cleanImportEntry{Name: name}
	}
	return entries
}

func ordinalImports(ordinals ...uint16) []cleanImportEntry {
	entries := make([]cleanImportEntry, len(ordinals))
	for index, ordinal := range ordinals {
		entries[index] = cleanImportEntry{Ordinal: ordinal}
	}
	return entries
}
